import Link from 'next/link'
import './styles/globals.css'
import styles from './styles/Home.module.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <main className={styles.main}>
          <nav>
            <Link href="/">
              Home
            </Link>
            <Link href="/posts">
              Posts
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
